### ISSUE TITLE
A possible incorrect representation of memory cell addresses in some figures

### ISSUE THREAD

**Issue by leelavg** [eborin/riscv-programming#1]
Hi,

From figures 6.2 to 6.11, shouldn't Main Memory represent the addresses as `8000, 8004, 8008, 800c` but not as `8000, 8001, 8002, 8003` as each memory cell is shown holding 4 bytes/2 hex digits?

Please disregard if I understood incorrectly.

Thanks.

**Comment by eborin** [comment]
Dear Leela Gangavarapu,

The figures are correct. Notice that the RISC-V memory is byte-addressable,
which means each memory cell holds 1 byte and is assigned an exclusive
address.
They are intended to illustrate the effect of  loading words (4 bytes),
halfwords (2 bytes), and bytes (1 bytes) from/to memory to/from registers
(which always hold 4 bytes).

Regards,

--
Prof. Edson Borin
Institute of Computing
Unicamp


Em sex., 17 de mar. de 2023 às 01:05, Leela Gangavarapu <
***@***.***> escreveu:

**Comment by leelavg** [comment]
- Thanks a lot for your time explaining this.
- I got confused in realizing that one hex digit equals a nibble.

Nevertheless, thanks for providing this excellent book for free of cost.
